### ISSUE TITLE
Logins are sticky

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/DM#40]
Logins are sticky. Even after I log out, when I open dm again, I am automatically logged back in, and cannot figure out a way to permanently keep me logged out. While convenient, not secure? Also, prevents me from testing public accounts, though this is more a personal issue. 

- Should always log out on close
- Click logout, still shows you logged in
- Back button returns to page where user still appears to be logged in
- Blank page after logout redirect persists

**Comment by jamiefolsom** [comment]
More research needed on this. Not sure this is a security issue. To test other accounts, we can use an [incognito window](https://support.google.com/chrome/answer/95464?source=gsearch&hl=en).

**Comment by jamiefolsom** [comment]
Update on this issue. HTTP Basic Authentication, which is what's being used on DM at the moment, apparently doesn't provide for a way for users to log out. Currently, a strategy is being used which involves logging in again, but providing incorrect credentials. Normally, when the user closes the browser, the authentication should be reset, but given our rather sophisticated data syncing scheme, I believe that user credentials are getting stored in the data store, and therefore, not removed upon browser close. More soon.

**Comment by SteveMarvin** [comment]
I am not having this issue. If I log out, I stay out. If I shut down, I have to log back in afterwards. Cannot reproduce.

**Comment by gremid** [comment]
The "sticky" logins have been a side-effect of specific browser setups caching HTTP Basic authentication credentials and submitting them to DM but not confirming (re-)authentication with the user. 

Given the OAuth2-based authentication workflow and a session-based login context where logouts happen via session invalidation, this should be fixed.

**Comment by SteveMarvin** [comment]
There is still a problem in that the user will have to delete cookies in order to be able to log in on the same machine with a different account. When I log back in after logging out, I am not given the opportunity to enter a different login. This has been a bit of a pain during testing.

**Comment by gremid** [comment]
@SteveMarvin, when a user logs out of DM, her reference to the account is properly removed on the server side, AFAIK. Authentication providers like Google or GitHub "remember you" though, should you opt to let them (as most people do).

When you log into DM with the same provider again, i.e. Gitub, DM in fact redirects you to the provider in order to authenticate. It now depends on the provider's policy, whether it asks for credentials, let you choose among different accounts, or whether the provider simply reuses the authentication context you have provided credentials for the last time.

I am afraid, we cannot do much about that, and maybe for users returning to DM regularly, this might actually be seen as a feature of the whole mechanism. I agree though, that it is a painful setup when testing with different accounts.

Would you agree that this is specific to testing, or should I investigate this further? (I am fairly new to OAuth.)

**Comment by SteveMarvin** [comment]
Between incognito windows and clearing cookies and cache, I can work around it. 👍  As long as we are not concerned about it for security or other reasons, I'm fine.
